"""Shareable synthetic demo-bundle generation.

The bundle created here is intentionally synthetic-only: it exercises the same
analysis and report surfaces as a real audit while remaining safe to publish in
docs, releases, and conference-style demonstrations.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from ..analysis import audit_summary_dict, run_dose_audit, write_audit_outputs
from ..report import generate_dose_report
from .synthetic import generate_synthetic_dose_csv

SYNTHETIC_DEMO_NOTE = (
    "This demo bundle contains only synthetic CT dose records generated by "
    "dicom-dose-audit. It contains no DICOM files, no PHI, and no clinical "
    "or regulatory determinations."
)


def write_synthetic_demo_bundle(
    output_dir: str | Path,
    *,
    n: int = 250,
    seed: int = 42,
    start_date: str = "2025-10-01",
    include_pdf: bool = True,
    force: bool = False,
) -> dict[str, Path]:
    """Write a complete synthetic demo bundle and return artifact paths."""
    out = Path(output_dir)
    if out.exists() and any(out.iterdir()) and not force:
        raise FileExistsError(
            f"{out} already contains files. Pass force=True or choose a new output directory."
        )

    out.mkdir(parents=True, exist_ok=True)
    data_dir = out / "data"
    analysis_dir = out / "analysis"
    report_dir = out / "report"

    synthetic_csv = data_dir / "synthetic_dose_data.csv"
    df = generate_synthetic_dose_csv(synthetic_csv, n=n, seed=seed, start_date=start_date)
    result = run_dose_audit(df, n_bootstrap=500)
    analysis_outputs = write_audit_outputs(result, analysis_dir)
    report = generate_dose_report(
        result,
        report_dir,
        basename="synthetic_dicom_dose_audit_report",
        include_pdf=include_pdf,
    )

    readme = out / "README.md"
    screenshot_guide = out / "SCREENSHOT_GUIDE.md"
    manifest = out / "manifest.json"

    readme.write_text(_readme_text(n=n, seed=seed, start_date=start_date), encoding="utf-8")
    screenshot_guide.write_text(_screenshot_guide_text(report.html), encoding="utf-8")
    manifest.write_text(
        json.dumps(
            _manifest_payload(
                out=out,
                n=n,
                seed=seed,
                start_date=start_date,
                synthetic_csv=synthetic_csv,
                analysis_outputs=analysis_outputs,
                report_html=report.html,
                report_pdf=report.pdf,
                report_pdf_error=report.pdf_error,
                summary=audit_summary_dict(result),
            ),
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )

    artifacts: dict[str, Path] = {
        "readme": readme,
        "manifest": manifest,
        "screenshot_guide": screenshot_guide,
        "synthetic_csv": synthetic_csv,
        "report_html": report.html,
        **{f"analysis_{name}": path for name, path in analysis_outputs.items()},
    }
    if report.pdf is not None:
        artifacts["report_pdf"] = report.pdf
    if report.pdf_error is not None:
        artifacts["report_pdf_error"] = report.pdf_error
    return artifacts


def _manifest_payload(
    *,
    out: Path,
    n: int,
    seed: int,
    start_date: str,
    synthetic_csv: Path,
    analysis_outputs: dict[str, Path],
    report_html: Path,
    report_pdf: Path | None,
    report_pdf_error: Path | None,
    summary: dict[str, Any],
) -> dict[str, Any]:
    files = {
        "synthetic_csv": _relative_posix(synthetic_csv, out),
        "report_html": _relative_posix(report_html, out),
        "analysis": {name: _relative_posix(path, out) for name, path in analysis_outputs.items()},
    }
    if report_pdf is not None:
        files["report_pdf"] = _relative_posix(report_pdf, out)
    if report_pdf_error is not None:
        files["report_pdf_error"] = _relative_posix(report_pdf_error, out)

    return {
        "bundle_type": "synthetic_demo",
        "synthetic": True,
        "contains_phi": False,
        "contains_dicom": False,
        "disclaimer": SYNTHETIC_DEMO_NOTE,
        "generator": "dicom-dose-audit synthetic demo bundle",
        "parameters": {
            "n": n,
            "seed": seed,
            "start_date": start_date,
        },
        "summary": summary,
        "files": files,
    }


def _readme_text(*, n: int, seed: int, start_date: str) -> str:
    return f"""# DICOM Dose Audit Synthetic Demo Bundle

{SYNTHETIC_DEMO_NOTE}

## Contents

- `data/synthetic_dose_data.csv` - generated CT dose records with planted quality issues.
- `analysis/` - machine-readable CSV and JSON audit outputs.
- `report/synthetic_dicom_dose_audit_report.html` - shareable HTML report.
- `report/synthetic_dicom_dose_audit_report.pdf` - optional PDF report when PDF generation succeeds.
- `manifest.json` - reproducibility metadata for the bundle.
- `SCREENSHOT_GUIDE.md` - suggested screenshots for documentation or a GitHub project page.

## Reproduce

```bash
dicom-dose-audit demo-bundle --output outputs/synthetic_demo_bundle --n {n} --seed {seed} --start-date {start_date}
```

Use `--no-pdf` if your local environment does not have PDF rendering dependencies available.

## Boundaries

This bundle is appropriate for screenshots, docs, workflow demonstrations, and software tests. It is not evidence of clinical safety, regulatory compliance, or real-world scanner performance.
"""


def _screenshot_guide_text(report_html: Path) -> str:
    return f"""# Screenshot Guide

Open `{_relative_posix(report_html, report_html.parents[1])}` and capture:

1. The report header and top-line summary cards.
2. The protocol-level dose summary table.
3. One dose distribution plot.
4. The statistical outlier section, including the safety disclaimer.

Before publishing screenshots, confirm the page title and bundle README still indicate synthetic-only data.
"""


def _relative_posix(path: Path, base: Path) -> str:
    return path.relative_to(base).as_posix()
