"""HTML and optional PDF report generation for the CT dose audit.

Dual-engine PDF strategy (matches the sibling rad-ai-sentinel project):
  - **Primary**: WeasyPrint (full CSS layout, requires GTK3 on Windows)
  - **Fallback**: fpdf2 (pure Python, no native deps, uses DejaVu Sans if available)

The report embeds boxplots (dose by protocol, by scanner) and monthly trend
plots generated by :mod:`dicom_dose_audit.plots`. Every surface carries the
safety disclaimer: flagged studies are statistical outliers, not clinical-
safety determinations.
"""

from __future__ import annotations

import io
import logging
from dataclasses import dataclass
from importlib.resources import files
from pathlib import Path

import pandas as pd
from jinja2 import Environment, select_autoescape
from markupsafe import Markup

from ..analysis import DoseAuditResult, audit_summary_dict, summary_metrics_frame
from ..analytics.comparisons import comparisons_dataframe
from ..analytics.missing import missing_dose_dataframe
from ..analytics.outliers import outliers_dataframe
from ..analytics.trends import trends_dataframe
from ..config import COL_CTDI_VOL, COL_DLP, SAFETY_DISCLAIMER
from ..plots import boxplot_by_protocol, boxplot_by_scanner, monthly_trend_plot

logger = logging.getLogger(__name__)

# Shared color palette (WeasyPrint CSS + fpdf2 fallback).
INK = "#1e2329"
MUTED = "#64707d"
LINE = "#d7dde5"
PANEL = "#f5f7fa"
BLUE = "#1769aa"
GREEN = "#1f7a4d"
ORANGE = "#b54d12"




@dataclass(frozen=True)
class ReportArtifacts:
    """Generated report paths."""

    html: Path
    pdf: Path | None
    pdf_error: Path | None = None


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------


def generate_dose_report(
    data: pd.DataFrame | DoseAuditResult,
    output_dir: str | Path,
    *,
    basename: str = "dicom_dose_audit_report",
    include_pdf: bool = True,
) -> ReportArtifacts:
    """Render a complete dose audit report."""
    # Local import to avoid a circular dependency at module load time.
    from ..analysis import run_dose_audit

    result = data if isinstance(data, DoseAuditResult) else run_dose_audit(data)
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    html = render_report_html(result)
    html_path = out / f"{basename}.html"
    html_path.write_text(html, encoding="utf-8")

    pdf_path: Path | None = None
    error_path: Path | None = None
    if include_pdf:
        pdf_path = out / f"{basename}.pdf"
        try:
            _write_pdf_weasyprint(html, pdf_path, out)
        except Exception as exc:
            logger.info("WeasyPrint PDF failed (%s), falling back to fpdf2", exc)
            try:
                _write_pdf_fpdf2(result, pdf_path)
            except Exception as exc2:
                logger.warning("fpdf2 PDF also failed (%s), writing error file", exc2)
                pdf_path = None
                error_path = out / f"{basename}.pdf.error.txt"
                error_path.write_text(
                    f"WeasyPrint error:\n{exc}\n\nfpdf2 fallback error:\n{exc2}\n",
                    encoding="utf-8",
                )

    return ReportArtifacts(html=html_path, pdf=pdf_path, pdf_error=error_path)


# ---------------------------------------------------------------------------
# WeasyPrint PDF (primary engine)
# ---------------------------------------------------------------------------


def _write_pdf_weasyprint(html: str, pdf_path: Path, base_url: Path) -> None:
    """Generate PDF using WeasyPrint. Raises on failure."""
    from weasyprint import HTML

    HTML(string=html, base_url=str(base_url)).write_pdf(pdf_path)


# ---------------------------------------------------------------------------
# fpdf2 PDF fallback (pure Python, no native deps)
# ---------------------------------------------------------------------------


def _hex_to_rgb(h: str) -> tuple[int, int, int]:
    """Convert ``'#RRGGBB'`` to ``(r, g, b)``."""
    h = h.lstrip("#")
    return int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)


def _find_dejavu_sans() -> Path | None:
    """Locate *DejaVuSans.ttf* on the system for Unicode PDF rendering."""
    candidates = [
        Path("C:/Windows/Fonts/DejaVuSans.ttf"),
        Path("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"),
        Path("/System/Library/Fonts/DejaVuSans.ttf"),
    ]
    for p in candidates:
        if p.is_file():
            return p
    return None


def _register_fonts(pdf: object) -> str:
    """Register Unicode fonts and return the font family name to use."""
    dejavu = _find_dejavu_sans()
    if dejavu:
        d = dejavu.parent
        pdf.add_font("DejaVu", "", str(d / "DejaVuSans.ttf"), uni=True)
        pdf.add_font("DejaVu", "B", str(d / "DejaVuSans-Bold.ttf"), uni=True)
        pdf.add_font("DejaVu", "I", str(d / "DejaVuSans-Oblique.ttf"), uni=True)
        pdf.add_font("DejaVu", "BI", str(d / "DejaVuSans-BoldOblique.ttf"), uni=True)
        return "DejaVu"
    return "Helvetica"  # built-in latin-1 fallback


def _write_pdf_fpdf2(result: DoseAuditResult, pdf_path: Path, font_family: str = "Helvetica") -> None:
    """Generate a styled PDF using fpdf2 as a cross-platform fallback."""
    from fpdf import FPDF

    summary = audit_summary_dict(result)
    pdf = FPDF(orientation="P", unit="mm", format="A4")
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.set_margins(15, 15, 15)

    font_family = _register_fonts(pdf)

    # --- Cover / Header ---
    pdf.add_page()
    _pdf_header(pdf, summary, font_family)
    _pdf_kpi_boxes(pdf, summary, font_family)

    # --- Protocol summary table ---
    _pdf_section(pdf, "Protocol-Level Dose Summary", font_family=font_family)
    _pdf_table(pdf, summary_metrics_frame(result), font_family)

    # --- Plots ---
    pdf.add_page()
    _pdf_section(pdf, "CTDIvol by Protocol", font_family=font_family)
    _pdf_embed_plot(pdf, boxplot_by_protocol(result.dataframe, COL_CTDI_VOL))
    _pdf_section(pdf, "DLP by Protocol", font_family=font_family)
    _pdf_embed_plot(pdf, boxplot_by_protocol(result.dataframe, COL_DLP))

    pdf.add_page()
    _pdf_section(pdf, "CTDIvol by Scanner", font_family=font_family)
    _pdf_embed_plot(pdf, boxplot_by_scanner(result.dataframe, COL_CTDI_VOL))
    _pdf_section(pdf, "Monthly Dose Trends (CTDIvol)", font_family=font_family)
    trend_df = trends_dataframe(result.trends)
    _pdf_embed_plot(pdf, monthly_trend_plot(trend_df, COL_CTDI_VOL))

    # --- Outliers ---
    pdf.add_page()
    _pdf_section(pdf, "Statistical Outliers", font_family=font_family)
    _pdf_caveat(pdf, font_family)
    outliers_df = outliers_dataframe(result.outliers)
    if outliers_df.empty:
        pdf.set_font(font_family, "I", 10)
        pdf.set_text_color(*_hex_to_rgb(MUTED))
        pdf.cell(0, 6, "No statistical outliers flagged.", new_x="LMARGIN", new_y="NEXT")
    else:
        _pdf_table(pdf, outliers_df, font_family)

    # --- Version comparison ---
    _pdf_section(pdf, "Protocol-Version Comparison", font_family=font_family)
    versions_df = comparisons_dataframe(result.version_comparisons)
    if versions_df.empty:
        pdf.set_font(font_family, "I", 10)
        pdf.set_text_color(*_hex_to_rgb(MUTED))
        pdf.cell(
            0, 6, "No protocols with multiple versions were available.",
            new_x="LMARGIN", new_y="NEXT",
        )
    else:
        _pdf_table(pdf, versions_df, font_family)

    # --- Missing dose ---
    _pdf_section(pdf, "Missing-Dose Analysis", font_family=font_family)
    _pdf_table(pdf, missing_dose_dataframe(result.missing), font_family)

    # --- Disclaimer ---
    pdf.ln(8)
    pdf.set_draw_color(*_hex_to_rgb(LINE))
    pdf.line(15, pdf.get_y(), 195, pdf.get_y())
    pdf.ln(4)
    pdf.set_font(font_family, "I", 8)
    pdf.set_text_color(*_hex_to_rgb(MUTED))
    pdf.multi_cell(0, 4, SAFETY_DISCLAIMER)

    pdf.output(str(pdf_path))


# ---- fpdf2 helper functions ----


def _pdf_header(pdf: object, summary: dict, font_family: str = "Helvetica") -> None:
    """Render the report header block."""
    pdf.set_font(font_family, "B", 9)
    pdf.set_text_color(*_hex_to_rgb(BLUE))
    pdf.cell(0, 5, "CT RADIATION-DOSE QUALITY IMPROVEMENT AUDIT", new_x="LMARGIN", new_y="NEXT")

    pdf.set_font(font_family, "B", 22)
    pdf.set_text_color(*_hex_to_rgb(INK))
    pdf.cell(0, 12, "dicom-dose-audit Report", new_x="LMARGIN", new_y="NEXT")

    pdf.set_font(font_family, "", 10)
    pdf.set_text_color(*_hex_to_rgb(MUTED))
    subtitle = (
        f"{summary['start_date']} to {summary['end_date']}  |  "
        f"{summary['n_studies']} studies  |  "
        f"{summary['n_protocols']} protocols  |  "
        f"{summary['n_outliers']} statistical outliers"
    )
    pdf.cell(0, 6, subtitle, new_x="LMARGIN", new_y="NEXT")

    pdf.ln(3)
    pdf.set_draw_color(*_hex_to_rgb(LINE))
    pdf.set_line_width(0.8)
    pdf.line(15, pdf.get_y(), 195, pdf.get_y())
    pdf.ln(8)


def _pdf_kpi_boxes(pdf: object, summary: dict, font_family: str = "Helvetica") -> None:
    """Render four KPI metric boxes in a row."""
    box_w = 40.5
    box_h = 22
    gap = 3.5
    start_x = 15
    y = pdf.get_y()

    metrics = [
        ("Studies", str(summary["n_studies"]), "total audited"),
        ("Outliers", str(summary["n_outliers"]), "flagged, not unsafe"),
        ("Missing CTDIvol", str(summary["n_studies_missing_ctdi"]), "studies"),
        ("Missing DLP", str(summary["n_studies_missing_dlp"]), "studies"),
    ]

    for i, (label, value, desc) in enumerate(metrics):
        x = start_x + i * (box_w + gap)
        pdf.set_fill_color(*_hex_to_rgb(PANEL))
        pdf.set_draw_color(*_hex_to_rgb(LINE))
        pdf.rect(x, y, box_w, box_h, style="DF")
        pdf.set_xy(x + 3, y + 2)
        pdf.set_font(font_family, "", 8)
        pdf.set_text_color(*_hex_to_rgb(MUTED))
        pdf.cell(box_w - 6, 4, label, new_x="LMARGIN", new_y="NEXT")
        pdf.set_xy(x + 3, y + 7)
        pdf.set_font(font_family, "B", 16)
        pdf.set_text_color(*_hex_to_rgb(INK))
        pdf.cell(box_w - 6, 8, value, new_x="LMARGIN", new_y="NEXT")
        pdf.set_xy(x + 3, y + 15)
        pdf.set_font(font_family, "", 7)
        pdf.set_text_color(*_hex_to_rgb(MUTED))
        pdf.cell(box_w - 6, 4, desc, new_x="LMARGIN", new_y="NEXT")

    pdf.set_y(y + box_h + 8)


def _pdf_caveat(pdf: object, font_family: str = "Helvetica") -> None:
    """Render the outlier-safety caveat box."""
    pdf.set_fill_color(255, 248, 230)
    pdf.set_draw_color(*_hex_to_rgb(ORANGE))
    pdf.set_xy(15, pdf.get_y())
    pdf.set_font(font_family, "I", 9)
    pdf.set_text_color(*_hex_to_rgb(INK))
    pdf.multi_cell(
        0, 5,
        "Flagged studies are statistical outliers within their protocol group. "
        "This is NOT a clinical-safety determination.",
        border="L",
        fill=True,
    )
    pdf.ln(3)


def _pdf_section(pdf: object, title: str, spacing: int = 1, font_family: str = "Helvetica") -> None:
    """Render a section heading."""
    pdf.ln(spacing * 4)
    pdf.set_font(font_family, "B", 14)
    pdf.set_text_color(*_hex_to_rgb(INK))
    pdf.cell(0, 8, title, new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)


def _pdf_table(pdf: object, df: pd.DataFrame, font_family: str = "Helvetica") -> None:
    """Render a pandas DataFrame as a styled table in the PDF."""
    if df.empty:
        pdf.set_font(font_family, "I", 10)
        pdf.set_text_color(*_hex_to_rgb(MUTED))
        pdf.cell(0, 6, "No data.", new_x="LMARGIN", new_y="NEXT")
        return

    cols = [str(c) for c in df.columns]
    col_count = len(cols)

    available_w = 180
    col_w = available_w / col_count
    if col_w < 18:
        col_w = 18

    if col_count * col_w > available_w:
        pdf.add_page(orientation="L")
        col_w = 257 / col_count

    row_h = 6

    pdf.set_font(font_family, "B", 8)
    pdf.set_fill_color(*_hex_to_rgb(PANEL))
    pdf.set_text_color(*_hex_to_rgb(INK))
    for col_name in cols:
        pdf.cell(col_w, row_h, col_name[:24], border=1, fill=True, new_x="RIGHT", new_y="TOP")
    pdf.ln(row_h)

    pdf.set_font(font_family, "", 8)
    pdf.set_text_color(*_hex_to_rgb(INK))
    for _, row in df.iterrows():
        if pdf.get_y() + row_h > pdf.h - 20:
            pdf.add_page()
            pdf.set_font(font_family, "B", 8)
            pdf.set_fill_color(*_hex_to_rgb(PANEL))
            for col_name in cols:
                pdf.cell(col_w, row_h, col_name[:24], border=1, fill=True, new_x="RIGHT", new_y="TOP")
            pdf.ln(row_h)
            pdf.set_font(font_family, "", 8)

        for col_name in cols:
            val = row[col_name]
            if pd.isna(val):
                text = ""
            elif isinstance(val, float):
                text = f"{val:.4g}"
            else:
                text = str(val)
            pdf.cell(col_w, row_h, text[:28], border=1, new_x="RIGHT", new_y="TOP")
        pdf.ln(row_h)

    pdf.ln(4)


def _pdf_embed_plot(pdf: object, data_uri: str) -> None:
    """Embed a base-64 data-URI PNG plot into the PDF."""
    if not data_uri:
        return
    import base64

    # Strip the "data:image/png;base64," prefix.
    _, _, b64 = data_uri.partition(",")
    if not b64:
        return
    try:
        img_bytes = base64.b64decode(b64)
    except Exception:
        return
    buf = io.BytesIO(img_bytes)
    img_w = 160
    img_h = img_w * 0.65
    pdf.image(buf, x=15, w=img_w, h=img_h)
    pdf.ln(6)


# ---------------------------------------------------------------------------
# HTML rendering (shared Jinja2 template)
# ---------------------------------------------------------------------------


def render_report_html(result: DoseAuditResult) -> str:
    """Render the report into an HTML string."""
    template_text = files("dicom_dose_audit.report").joinpath("templates", "report.html").read_text()
    css = files("dicom_dose_audit.report").joinpath("templates", "styles.css").read_text()
    env = Environment(autoescape=select_autoescape(["html", "xml"]))
    template = env.from_string(template_text)

    summary = audit_summary_dict(result)
    trend_df = trends_dataframe(result.trends)

    return template.render(
        css=Markup(css),
        start_date=summary["start_date"],
        end_date=summary["end_date"],
        n=summary["n_studies"],
        n_protocols=summary["n_protocols"],
        n_outliers=summary["n_outliers"],
        missing_ctdi=summary["n_studies_missing_ctdi"],
        missing_dlp=summary["n_studies_missing_dlp"],
        summary_table=_to_html(summary_metrics_frame(result)),
        outliers_table=_to_html(outliers_dataframe(result.outliers), empty="No statistical outliers flagged."),
        versions_table=_to_html(
            comparisons_dataframe(result.version_comparisons),
            empty="No protocols with multiple versions were available.",
        ),
        missing_table=_to_html(missing_dose_dataframe(result.missing)),
        boxplot_ctdi_protocol=boxplot_by_protocol(result.dataframe, COL_CTDI_VOL),
        boxplot_dlp_protocol=boxplot_by_protocol(result.dataframe, COL_DLP),
        boxplot_ctdi_scanner=boxplot_by_scanner(result.dataframe, COL_CTDI_VOL),
        trend_ctdi=monthly_trend_plot(trend_df, COL_CTDI_VOL),
        trend_dlp=monthly_trend_plot(trend_df, COL_DLP),
        disclaimer=SAFETY_DISCLAIMER,
    )


def _to_html(df: pd.DataFrame, *, empty: str = "No rows.") -> str:
    if df.empty:
        return f'<p class="empty">{empty}</p>'
    return df.to_html(index=False, classes="data-table", border=0, na_rep="")
